'@ConfigurationProperties': ''
server:
  port: 8080
spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/gira
    username: postgres
    password: admin
  jpa:
    hibernate:
    auto-ddl: update
    generate-ddl: true
    show-sql: true

  flyway:
    enabled: true
    driver-class-name: org.postgresql.Driver

